### ISSUE TITLE
make some changes on camera limitator and hit save, then do some other changes on camera limitator and hit save again cause save failure

### ISSUE THREAD

**Issue by shinespeciall** [wario-land/WL4Editor#230]
There is no data corruption directly on the rom, i mean the game can run without crash and the editor can load the rom.
Save failure will happen again after you closing the editor and open the rom in another editor, change the camera limitator and hit save.
It should be caused by chunk invalidation code, perhaps the pointer reset is fine.

**Comment by Goldensunboy** [comment]
Repro:
- Open a ROM
- Select "Camera" from the Edit Mode pane
- Change camera setting to "Use Camera Limitators"
- Click "+" to add a camera limitator
- Save ROM
- Press the up arrow on the limitator's X spinbox (changes from 2 to 3)
- Save ROM
- Observe that there is save chunk corruption and an error message in the output widget

**Comment by Goldensunboy** [comment]
The issue is that with camera limitators, there are 2 types of chunks; one of type CameraPointerTableType, and N chunks of type CameraBoundaryChunkType. The code which creates invalidation chunks for the old CameraBoundaryChunkType chunks (Level.cpp:355) uses the address of the pointers themselves in the CameraPointerTableType table, instead of the values of the pointers as they should. If unfixed, this causes unrecoverable chunk leak when saving levels with camera limitators.

**Comment by Goldensunboy** [comment]
There is an additional bug here which is also causing chunk leak within the if-block at Level.cpp:327:
- When changing from camera limitators to another type (like fixed), then invalidation chunks are not created for existing limitators

**Comment by shinespeciall** [comment]
current solution: if you really want to use the feature with some unknown risk, you can use beta-9 build.
