### ISSUE TITLE
Changing Layer 0 Mapping Type to Tile8x8 related value will crash the editor

### ISSUE THREAD

**Issue by becored** [wario-land/WL4Editor#245]
- Open a ROM
- Load Level: Sapphire Passage - Third Level (Fiery Cavern)
- Switch to Room 2
- Open Room Config
- Change Layer 0 Mapping Type to "0"(Disabled) from "22"(Tile8x8 & autoscroll)
- Press OK (close Room Config)
- Open Room Config
- Change Layer 0 Mapping Type to "22"(Tile8x8 & autoscroll) from "0"(Disabled)
- Press OK (close Room Config)
- The editor crashes

**Comment by shinespeciall** [comment]
it turns out to be that we cannot apply changes for layer 0 be set mapping type equal to or over 0x20 because there is no available layer data suit for this case in most of the Tileset, so most of the time, set layer 0 mapping type to be something like 0x2X will crash the editor when it try to apply changes, using address 0 as the new layer compressed data saving places and try to decompressed data from offset 0 in the rom. 
The solution should be something like we make a new editor for users to create and edit current mapping type 0x2X layers.
and there will be another great project to add new code to the save things, undo & redo part, etc.
