### ISSUE TITLE
Making changes on Camera setting will crash the editor (related to #230)

### ISSUE THREAD

**Issue by becored** [wario-land/WL4Editor#263]
Repro:
- Open a ROM
- Select "Camera"
- Change camera setting to "Use Camera Limitators"
- Click "+" to add a camera limitator
- Save ROM
- Click "-" to remove a camera limitator
- Save ROM
- Change camera setting to "Follow Wario"
- Save ROM
- The editor crashes

**Comment by Goldensunboy** [comment]
Reproduced. Can confirm that clicking "-" to remove the only camera limitator and then saving is a necessary step to repro. But it shouldn't be valid to have a room in camera limitators mode with no limitators. Segfault due to infinitely searching for the camera sentinel while creating invalidation chunks for the old camera boundary chunks.

Suggested fix:
- Auto-populate camera limitators list with one limitator when switching to camera limitators mode
- Disallow user from removing the last camera limitator from the list
- Cause the save function to gracefully exit with a warning if camera sentinel is not found after 100 iterations

**Comment by becored** [comment]
Repro (from a hacked rom in attachment):
[20200914005131.zip](https://github.com/wario-land/WL4Editor/files/5214713/20200914005131.zip)
- Open a ROM
- Choose a level "Emerald Passage, Level 3"
- Edit > Add > New Room
- Change camera setting to "Follow Wario" in Room 12
- Save ROM
- Save error: Infinitely looping through camera boundary entries. Address: 0x79E430

**Comment by Goldensunboy** [comment]
Successful repro. Changing the camera setting is not necessary.

**Comment by Goldensunboy** [comment]
This occurs if you create a new room then save, while on a room which has camera limitators. It copies the room header setting that there are camera limitators, but not the limitators themselves. When saving, behavior is undefined when creating camera limitator chunks for the new room.

Suggested solution is to reset the camera type to "Follow Wario" automatically when creating a new room.

**Comment by shinespeciall** [comment]
Fixed.

**Comment by becored** [comment]
Apparently there is still a save corruption bug with Camera settings.

Repro:
- Open a vanilla ROM
- Move to Room 2 (in First Level of Entry Passage)
- Select "Camera"
- Change camera setting to "Follow Wario"
- Save ROM 
- Save ROM again
- Internal error while saving changes to ROM: Invalidation chunk references an invalid RATS identifier for existing chunk. Save chunk index: 7. Address: 0x50FE714. Changes not saved.
