### ISSUE TITLE
Making a change and saves on Camera setting will corrupt the rom file

### ISSUE THREAD

**Issue by becored** [wario-land/WL4Editor#284]
Apparently there is still a save corruption bug with Camera settings.

Repro:
- Open a vanilla ROM
- Move to Room 2 (in First Level of Entry Passage)
- Select "Camera"
- Change camera setting to "Follow Wario"
- Save ROM
- Save ROM again
- Internal error while saving changes to ROM: Invalidation chunk references an invalid RATS identifier for existing chunk. Save chunk index: 7. Address: 0x50FE714. Changes not saved.

**Comment by Goldensunboy** [comment]
Successful repro. Can confirm this only happens on rooms with camera limitators. When creating invalidation chunks for existing camera limitators in this scenario, the camera boundary pointer table chunk has an extra entry at the end with garbage in it.

This happens because when it is setting up the size for the camera boundary pointer table chunk, it checks if the camera limitators vector in each room is not equal to size 0. But, changing the camera type from limitators does not empty this vector. Thus, the check for getting the count of limitator rooms is incorrect.

Suggested fix is to instead directly check the camera type for the room.
