### ISSUE TITLE
Making changes on Spriteset Load Table and Door Config will corrupt the rom file

### ISSUE THREAD

**Issue by becored** [wario-land/WL4Editor#300]
Repro:
- Open a vanilla ROM
- Edit > Edit Entities and EntitySets
- Load Spriteset ID: 83 (blank area)
- Set Spriteset Load Table: 58 00 59 00 5a 00 5b 00 5c 00 57 00 23 02 24 02 25 02 22 03 72 04 4e 05 (same values as Spriteset ID: 42)
- Reset then OK
- Save ROM
- Close and reopen the rom
- Select any door and open Door Config
- Select EntitySet ID: 83
- Press OK
- Save ROM
- Close and reopen the rom
- Output window message says "load entityset error: loading palette's id out of bound.entityset id: 83"
- Edit > Edit Entities and EntitySets
- Load Spriteset ID: 83
- The editor crashes

**Comment by shinespeciall** [comment]
![image](https://user-images.githubusercontent.com/28697038/99974299-b0aabf80-2ddb-11eb-8aac-d9c9b9e84ae5.png)
this part of data looks incorrect when it crashes

**Comment by shinespeciall** [comment]
![image](https://user-images.githubusercontent.com/28697038/99975442-311df000-2ddd-11eb-9990-a1c513292d28.png)
the second save create some save chunk corrupted the old chunks

**Comment by Goldensunboy** [comment]
The error appears to be somewhere in the ROMUtils::FindAllFreeSpaceInROM function, which is saying that 0x78FE7E is considered free space (it is aligned to 0x78FE80 which is where the corruption occurs). This address is coincidentally exactly 12 bytes behind the actual free space, which is the same size as an RATS header. This can be verified by setting a conditional breakpoint in ROMUtils.cpp:476 with "freeSpaceStart == 0x78fe7e"

When this function is looking for free space, it takes some starting address, and goes until it finds a valid RATS tag. Once it finds one, it notes that free space was found, then continues the search after the valid chunk. The math in determining this area to resume the search is incorrect because it does not factor in the 12-byte RATS header size.

The solution is to add 12 to the location that the FindAllFreeSpaceInROM function resumes its free space search after successfully finding a free space chunk.
