### ISSUE TITLE
No more info dialog when setting door type to type 1 (portal & door) in Door Config Dialog

### ISSUE THREAD

**Issue by Goldensunboy** [wario-land/WL4Editor#322]
Requested feature

**Comment by shinespeciall** [comment]
oh, it hits me that there are a lot of doors using type 1 in some levels, so we don't need that dialog any more
i added that dialog at first because i thought we never use door type 1 somewhere else except the protal
so the solution of this is that we just delete that dialog, no more wrong useless warnings
