### ISSUE TITLE
importing tileset from other rom will cause problem when opening Room Config Dialog

### ISSUE THREAD

**Issue by becored** [wario-land/WL4Editor#402]
Repro:
- Open a vanilla rom
- File > Import from ROM > Import Tileset
- Select a vanilla rom
- Input "50" and click OK
- Edit > Room Config
- Error: Unknown BG tile data pointer!

**Comment by shinespeciall** [comment]
oh, that's some problem in the UI logic.
after the implementation of Graphic Manager, we can change background tiles in Tilesets. since the backgroud data are managed by the manager, we cannot import them when import Tileset from another ROM. so i let the editor use a default bg tile data pointer to deal with this problem.
but that will cause some problem in the Room Config Dialog that, it cannot recognize default bg tile data by refering the bg tile data used by the vanilla Tileset of the current global id, and it also cannot find any graphic entry exist in the ROM managed by the Graphic Manager, so it shows the Error Dialog. your ROM didn't get corrupted, it is some UI logic problems.
i can changed the UI logic, and let it check every vanilla bg tile data, and see if any of them match the pointer, then there will be no problem managing Layer 3 mapping data in the Room Config Dialog. you can even do something like, let Tileset 0x01 use the bg tile data from Tileset 0x02, then import the Tileset into another ROM. the Room Config Dialog should still work in the new UI logic.
